### ISSUE TITLE
404 on pgdg-centos11-11-2.noarch.rpm 

### ISSUE THREAD

**Issue by BenHall** [CrunchyData/crunchy-katacoda#10]
![Screenshot 2019-04-12 08 58 15](https://user-images.githubusercontent.com/82614/56021363-221a2500-5d01-11e9-86df-241b7705f56b.png)

Looks like it's been removed from https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/

@thesteve0

**Comment by BenHall** [comment]
Looks like something has gone wrong upstream as the download only lists ppc64le

https://www.postgresql.org/download/linux/redhat/

**Comment by thesteve0** [comment]
Should be fixed please try a rebuild

**Comment by BenHall** [comment]
@thesteve0 Failing again

404 on https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/pgdg-centos11-11-2.noarch.rpm

**Comment by thesteve0** [comment]
Seems to be fixed and I also fixed the data download

**Comment by BenHall** [comment]
Thanks, must have caught it at the wrong time.
