### ISSUE TITLE
Make the course/scenario nested directory structure

### ISSUE THREAD

**Issue by thesteve0** [CrunchyData/crunchy-katacoda#22]
@BenHall please set up the nest structure. 
You can start with Workshops, PostGIS, and BasicPostgresqlDevel as top levels. PostGIS and BasicPostgresqlDevel will be empty for now

**Comment by BenHall** [comment]
When creating a new scenario, ensure it is added to a course. For example:

https://github.com/CrunchyData/crunchy-katacoda/blob/master/workshops-pathway.json
